export const PERMISSIONS = {
  AUTH_ME: 'auth:me',
  AUTH_ROLES_READ: 'auth:roles:read',
  AUTH_ROLES_WRITE: 'auth:roles:write',
  AUTH_PERMISSIONS_READ: 'auth:permissions:read',
  AUTH_PERMISSIONS_WRITE: 'auth:permissions:write',
  ORG_READ: 'org:read',
  ORG_WRITE: 'org:write',
  EMPLOYEES_READ: 'employees:read',
  EMPLOYEES_WRITE: 'employees:write',
  EMPLOYEES_ME_READ: 'employees:me:read',
  EMPLOYEES_DOCUMENTS_READ: 'employees:documents:read',
  EMPLOYEES_DOCUMENTS_WRITE: 'employees:documents:write',
  EMPLOYEES_CHANGE_REQUEST_CREATE: 'employees:change-request:create',
  EMPLOYEES_CHANGE_REQUEST_READ: 'employees:change-request:read',
  EMPLOYEES_CHANGE_REQUEST_REVIEW: 'employees:change-request:review',
  ATTENDANCE_ME_PUNCH: 'attendance:me:punch',
  ATTENDANCE_ME_READ: 'attendance:me:read',
  ATTENDANCE_DASHBOARD: 'attendance:dashboard',
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_SHIFTS_WRITE: 'attendance:shifts:write',
  ATTENDANCE_EXPORT: 'attendance:export',
  LEAVE_REQUESTS_CREATE: 'leave:requests:create',
  LEAVE_BALANCES_ME: 'leave:balances:me',
  LEAVE_REQUESTS_ME: 'leave:requests:me',
  LEAVE_REQUESTS_APPROVE: 'leave:requests:approve',
  LEAVE_REQUESTS_READ: 'leave:requests:read',
  LEAVE_TYPES_WRITE: 'leave:types:write',
  LEAVE_POLICIES_WRITE: 'leave:policies:write',
  NOTIFICATIONS_ME: 'notifications:me',
  PAYROLL_COMPONENTS_WRITE: 'payroll:components:write',
  PAYROLL_PROFILE_WRITE: 'payroll:profile:write',
  PAYROLL_RUNS_WRITE: 'payroll:runs:write',
  PAYROLL_RUNS_READ: 'payroll:runs:read',
  PAYROLL_EXPORT: 'payroll:export',
  PAYSLIPS_ME: 'payslips:me',
  RECRUITMENT_JOBS_READ: 'recruitment:jobs:read',
  RECRUITMENT_JOBS_WRITE: 'recruitment:jobs:write',
  RECRUITMENT_APPLICATIONS_READ: 'recruitment:applications:read',
  RECRUITMENT_APPLICATIONS_WRITE: 'recruitment:applications:write',
  RECRUITMENT_HIRE: 'recruitment:hire',
  ONBOARDING_TEMPLATES_WRITE: 'onboarding:templates:write',
  ONBOARDING_READ: 'onboarding:read',
  ONBOARDING_TASKS_COMPLETE: 'onboarding:tasks:complete',
  ONBOARDING_ME: 'onboarding:me',
} as const

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
