export const PERMISSIONS = {
  AUTH_ME: "auth:me",
  AUTH_ROLES_READ: "auth:roles:read",
  AUTH_ROLES_WRITE: "auth:roles:write",
  AUTH_PERMISSIONS_READ: "auth:permissions:read",
  AUTH_PERMISSIONS_WRITE: "auth:permissions:write",
  ORG_READ: "org:read",
  ORG_WRITE: "org:write",
  EMPLOYEES_READ: "employees:read",
  EMPLOYEES_WRITE: "employees:write",
  EMPLOYEES_ME_READ: "employees:me:read",
  EMPLOYEES_DOCUMENTS_READ: "employees:documents:read",
  EMPLOYEES_DOCUMENTS_WRITE: "employees:documents:write",
  EMPLOYEES_CHANGE_REQUEST_CREATE: "employees:change-request:create",
  EMPLOYEES_CHANGE_REQUEST_READ: "employees:change-request:read",
  EMPLOYEES_CHANGE_REQUEST_REVIEW: "employees:change-request:review",
  ATTENDANCE_ME_PUNCH: "attendance:me:punch",
  ATTENDANCE_ME_READ: "attendance:me:read",
  ATTENDANCE_DASHBOARD: "attendance:dashboard",
  ATTENDANCE_SHIFTS_WRITE: "attendance:shifts:write",
  ATTENDANCE_READ: "attendance:read",
  ATTENDANCE_EXPORT: "attendance:export",
  LEAVE_REQUESTS_CREATE: "leave:requests:create",
  LEAVE_BALANCES_ME: "leave:balances:me",
  LEAVE_REQUESTS_ME: "leave:requests:me",
  LEAVE_REQUESTS_APPROVE: "leave:requests:approve",
  LEAVE_REQUESTS_READ: "leave:requests:read",
  LEAVE_TYPES_WRITE: "leave:types:write",
  LEAVE_POLICIES_WRITE: "leave:policies:write",
  NOTIFICATIONS_ME: "notifications:me",
  PAYROLL_COMPONENTS_WRITE: "payroll:components:write",
  PAYROLL_PROFILE_WRITE: "payroll:profile:write",
  PAYROLL_RUNS_WRITE: "payroll:runs:write",
  PAYROLL_RUNS_READ: "payroll:runs:read",
  PAYSLIPS_ME: "payslips:me",
  PAYROLL_EXPORT: "payroll:export",
  RECRUITMENT_JOBS_READ: "recruitment:jobs:read",
  RECRUITMENT_JOBS_WRITE: "recruitment:jobs:write",
  RECRUITMENT_APPLICATIONS_READ: "recruitment:applications:read",
  RECRUITMENT_APPLICATIONS_WRITE: "recruitment:applications:write",
  RECRUITMENT_HIRE: "recruitment:hire",
  ONBOARDING_TEMPLATES_WRITE: "onboarding:templates:write",
  ONBOARDING_READ: "onboarding:read",
  ONBOARDING_TASKS_COMPLETE: "onboarding:tasks:complete",
  ONBOARDING_ME: "onboarding:me",
  PERFORMANCE_GOALS_READ: "performance:goals:read",
  PERFORMANCE_GOALS_WRITE: "performance:goals:write",
  PERFORMANCE_GOALS_APPROVE: "performance:goals:approve",
  PERFORMANCE_GOALS_ME: "performance:goals:me",
  PERFORMANCE_REVIEWS_READ: "performance:reviews:read",
  PERFORMANCE_REVIEWS_WRITE: "performance:reviews:write",
  PERFORMANCE_REVIEWS_ME: "performance:reviews:me",
  PERFORMANCE_CYCLES_WRITE: "performance:cycles:write",
  PERFORMANCE_DASHBOARD: "performance:dashboard",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSION_KEYS: readonly PermissionKey[] = Object.values(PERMISSIONS);

export const EMPLOYEE_ROLE_PERMISSIONS: readonly PermissionKey[] = [
  PERMISSIONS.AUTH_ME,
  PERMISSIONS.EMPLOYEES_ME_READ,
  PERMISSIONS.EMPLOYEES_CHANGE_REQUEST_CREATE,
  PERMISSIONS.EMPLOYEES_CHANGE_REQUEST_READ,
  PERMISSIONS.ATTENDANCE_ME_PUNCH,
  PERMISSIONS.ATTENDANCE_ME_READ,
  PERMISSIONS.LEAVE_REQUESTS_CREATE,
  PERMISSIONS.LEAVE_BALANCES_ME,
  PERMISSIONS.LEAVE_REQUESTS_ME,
  PERMISSIONS.NOTIFICATIONS_ME,
  PERMISSIONS.PAYSLIPS_ME,
  PERMISSIONS.ONBOARDING_ME,
  PERMISSIONS.ONBOARDING_TASKS_COMPLETE,
  PERMISSIONS.PERFORMANCE_GOALS_ME,
  PERMISSIONS.PERFORMANCE_REVIEWS_ME,
];

export const MANAGER_ROLE_PERMISSIONS: readonly PermissionKey[] = [
  ...EMPLOYEE_ROLE_PERMISSIONS,
  PERMISSIONS.ATTENDANCE_DASHBOARD,
  PERMISSIONS.LEAVE_REQUESTS_APPROVE,
  PERMISSIONS.ONBOARDING_READ,
  PERMISSIONS.PERFORMANCE_GOALS_READ,
  PERMISSIONS.PERFORMANCE_GOALS_APPROVE,
  PERMISSIONS.PERFORMANCE_REVIEWS_READ,
  PERMISSIONS.PERFORMANCE_REVIEWS_WRITE,
  PERMISSIONS.PERFORMANCE_DASHBOARD,
];

export const RECRUITER_ROLE_PERMISSIONS: readonly PermissionKey[] = [
  PERMISSIONS.AUTH_ME,
  PERMISSIONS.NOTIFICATIONS_ME,
  PERMISSIONS.RECRUITMENT_JOBS_READ,
  PERMISSIONS.RECRUITMENT_JOBS_WRITE,
  PERMISSIONS.RECRUITMENT_APPLICATIONS_READ,
  PERMISSIONS.RECRUITMENT_APPLICATIONS_WRITE,
  PERMISSIONS.ONBOARDING_READ,
  PERMISSIONS.ONBOARDING_TASKS_COMPLETE,
];

export const HR_ADMIN_ROLE = "hr_admin";
export const EMPLOYEE_ROLE = "employee";
export const MANAGER_ROLE = "manager";
export const RECRUITER_ROLE = "recruiter";
