export const endpoints = {
  health: '/health',
  ready: '/ready',
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/auth/me',
  },
  roles: '/roles',
  role: (id: string) => `/roles/${id}`,
  rolePermissions: (id: string) => `/roles/${id}/permissions`,
  permissions: '/permissions',
  employees: '/employees',
  employee: (id: string) => `/employees/${id}`,
  employeeOffboard: (id: string) => `/employees/${id}/offboard`,
  employeeMutations: (id: string) => `/employees/${id}/mutations`,
  employeeDocuments: (id: string) => `/employees/${id}/documents`,
  employeeDocument: (id: string, docId: string) => `/employees/${id}/documents/${docId}`,
  employeeDocumentFile: (id: string, docId: string) => `/employees/${id}/documents/${docId}/file`,
  employeesMe: '/employees/me',
  myChangeRequests: '/employees/me/change-requests',
  changeRequests: '/employees/change-requests',
  approveChangeRequest: (id: string) => `/employees/change-requests/${id}/approve`,
  rejectChangeRequest: (id: string) => `/employees/change-requests/${id}/reject`,
  orgTree: '/org/tree',
  departments: '/departments',
  department: (id: string) => `/departments/${id}`,
  positions: '/positions',
  position: (id: string) => `/positions/${id}`,
  attendance: {
    checkIn: '/attendance/check-in',
    checkOut: '/attendance/check-out',
    me: '/attendance/me',
    dashboard: '/attendance/dashboard',
    summary: '/attendance/summary',
    export: '/attendance/export',
    shifts: '/attendance/shifts',
    shift: (id: string) => `/attendance/shifts/${id}`,
    shiftAssignments: (id: string) => `/attendance/shifts/${id}/assignments`,
    employeeAssignments: (employeeId: string) => `/attendance/employees/${employeeId}/assignments`,
  },
  leave: {
    types: '/leave/types',
    type: (id: string) => `/leave/types/${id}`,
    policies: '/leave/policies',
    policy: (id: string) => `/leave/policies/${id}`,
    balancesMe: '/leave/balances/me',
    requestsMe: '/leave/requests/me',
    requests: '/leave/requests',
    approve: (id: string) => `/leave/requests/${id}/approve`,
    reject: (id: string) => `/leave/requests/${id}/reject`,
  },
  notificationsMe: '/notifications/me',
  notificationRead: (id: string) => `/notifications/${id}/read`,
  payroll: {
    components: '/payroll/components',
    component: (id: string) => `/payroll/components/${id}`,
    profiles: '/payroll/profiles',
    profile: (employeeId: string) => `/payroll/profiles/${employeeId}`,
    assignments: '/payroll/assignments',
    assignmentsFor: (employeeId: string) => `/payroll/assignments/${employeeId}`,
    runs: '/payroll/runs',
    run: (id: string) => `/payroll/runs/${id}`,
    runPayslips: (id: string) => `/payroll/runs/${id}/payslips`,
    exports: {
      accounting: (id: string) => `/payroll/runs/${id}/exports/accounting`,
      pph21: (id: string) => `/payroll/runs/${id}/exports/pph21`,
      a1: (id: string) => `/payroll/runs/${id}/exports/1721-a1`,
      bank: (id: string) => `/payroll/runs/${id}/exports/bank`,
    },
  },
  payslipsMe: '/payslips/me',
  payslip: (id: string) => `/payslips/${id}`,
  payslipPdf: (id: string) => `/payslips/${id}/pdf`,
  careers: '/careers',
  career: (slug: string) => `/careers/${slug}`,
  careerApply: (slug: string) => `/careers/${slug}/apply`,
  recruitment: {
    jobs: '/recruitment/jobs',
    job: (id: string) => `/recruitment/jobs/${id}`,
    jobStages: (id: string) => `/recruitment/jobs/${id}/stages`,
    jobApplications: (id: string) => `/recruitment/jobs/${id}/applications`,
    application: (id: string) => `/recruitment/applications/${id}`,
    applicationStage: (id: string) => `/recruitment/applications/${id}/stage`,
    applicationNotes: (id: string) => `/recruitment/applications/${id}/notes`,
    applicationReject: (id: string) => `/recruitment/applications/${id}/reject`,
    applicationHire: (id: string) => `/recruitment/applications/${id}/hire`,
  },
  onboarding: {
    templates: '/onboarding/templates',
    template: (id: string) => `/onboarding/templates/${id}`,
    templateItems: (id: string) => `/onboarding/templates/${id}/items`,
    item: (id: string) => `/onboarding/items/${id}`,
    dashboard: '/onboarding/dashboard',
    me: '/onboarding/me',
    process: (employeeId: string) => `/onboarding/processes/${employeeId}`,
    completeTask: (id: string) => `/onboarding/tasks/${id}/complete`,
  },
  performance: {
    goals: '/performance/goals',
    cycles: '/performance/cycles',
  },
} as const
