export const endpoints = {
  health: '/health',
  ready: '/ready',
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/auth/me',
  },
  roles: '/roles',
  role: (id: string) => `/roles/${id}`,
  rolePermissions: (id: string) => `/roles/${id}/permissions`,
  permissions: '/permissions',
  employees: '/employees',
  employee: (id: string) => `/employees/${id}`,
  employeeOffboard: (id: string) => `/employees/${id}/offboard`,
  employeeMutations: (id: string) => `/employees/${id}/mutations`,
  employeeDocuments: (id: string) => `/employees/${id}/documents`,
  employeeDocument: (id: string, docId: string) => `/employees/${id}/documents/${docId}`,
  employeeDocumentFile: (id: string, docId: string) => `/employees/${id}/documents/${docId}/file`,
  employeesMe: '/employees/me',
  myChangeRequests: '/employees/me/change-requests',
  changeRequests: '/employees/change-requests',
  approveChangeRequest: (id: string) => `/employees/change-requests/${id}/approve`,
  rejectChangeRequest: (id: string) => `/employees/change-requests/${id}/reject`,
  orgTree: '/org/tree',
  departments: '/departments',
  department: (id: string) => `/departments/${id}`,
  positions: '/positions',
  position: (id: string) => `/positions/${id}`,
  attendance: {
    checkIn: '/attendance/check-in',
    checkOut: '/attendance/check-out',
    me: '/attendance/me',
    dashboard: '/attendance/dashboard',
    summary: '/attendance/summary',
    export: '/attendance/export',
    shifts: '/attendance/shifts',
    shift: (id: string) => `/attendance/shifts/${id}`,
    shiftAssignments: (id: string) => `/attendance/shifts/${id}/assignments`,
    employeeAssignments: (employeeId: string) => `/attendance/employees/${employeeId}/assignments`,
  },
  leave: {
    types: '/leave/types',
    type: (id: string) => `/leave/types/${id}`,
    policies: '/leave/policies',
    policy: (id: string) => `/leave/policies/${id}`,
    balancesMe: '/leave/balances/me',
    requestsMe: '/leave/requests/me',
    requests: '/leave/requests',
    approve: (id: string) => `/leave/requests/${id}/approve`,
    reject: (id: string) => `/leave/requests/${id}/reject`,
  },
  notificationsMe: '/notifications/me',
  notificationRead: (id: string) => `/notifications/${id}/read`,
  payroll: {
    components: '/payroll/components',
    runs: '/payroll/runs',
  },
  payslipsMe: '/payslips/me',
  careers: '/careers',
  recruitmentJobs: '/recruitment/jobs',
  onboarding: {
    templates: '/onboarding/templates',
    dashboard: '/onboarding/dashboard',
    me: '/onboarding/me',
  },
  performance: {
    goals: '/performance/goals',
    cycles: '/performance/cycles',
  },
} as const
