export const endpoints = {
  health: '/health',
  ready: '/ready',
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/auth/me',
  },
  roles: '/roles',
  permissions: '/permissions',
  employees: '/employees',
  employeesMe: '/employees/me',
  orgTree: '/org/tree',
  departments: '/departments',
  positions: '/positions',
  attendance: {
    checkIn: '/attendance/check-in',
    checkOut: '/attendance/check-out',
    me: '/attendance/me',
    dashboard: '/attendance/dashboard',
    summary: '/attendance/summary',
    export: '/attendance/export',
    shifts: '/attendance/shifts',
  },
  leave: {
    types: '/leave/types',
    policies: '/leave/policies',
    balancesMe: '/leave/balances/me',
    requestsMe: '/leave/requests/me',
    requests: '/leave/requests',
    inbox: '/leave/inbox',
  },
  notificationsMe: '/notifications/me',
  payroll: {
    components: '/payroll/components',
    runs: '/payroll/runs',
  },
  payslipsMe: '/payslips/me',
  careers: '/careers',
  recruitmentJobs: '/recruitment/jobs',
  onboarding: {
    templates: '/onboarding/templates',
    dashboard: '/onboarding/dashboard',
    me: '/onboarding/me',
  },
  performance: {
    goals: '/performance/goals',
    cycles: '/performance/cycles',
  },
} as const
